// src/App.tsx
import { useState, useEffect, useCallback, useMemo } from "react";
import type maplibregl from "maplibre-gl";
import CoverMap from "./components/CoverMap";
import CoverModal from "./components/CoverModal";
import DatePicker from "./components/DatePicker";
import SearchBar from "./components/SearchBar";
import SearchMiniMap from "./components/SearchMiniMap";
import { findCoverByDate } from "./utils/coverLookup";
import type { CoverEntry } from "./utils/coverLookup";
import { initSearchIndex, searchCovers } from "./utils/searchIndex";
import {
  buildSearchResultIndices,
  getSearchResultPos,
  navigatePrev,
  navigateNext,
  buildResultLabel,
  computeHasPrev,
  computeHasNext,
} from "./utils/searchSession";
import "./styles/app.css";

const MIN_DATE = new Date(1946, 1, 21); // Feb 21, 1946
const MAX_DATE = new Date(2026, 1, 21); // Feb 21, 2026

export default function App() {
  const [covers, setCovers] = useState<CoverEntry[]>([]);
  const [selectedCover, setSelectedCover] = useState<CoverEntry | null>(null);
  const [selectedIndex, setSelectedIndex] = useState(0);
  const [flyToIndex, setFlyToIndex] = useState<number | null>(null);
  const [searchReady, setSearchReady] = useState(false);
  const [searchResults, setSearchResults] = useState<Map<string, number> | null>(null);
  const [searchResultCount, setSearchResultCount] = useState<number | null>(null);
  const [mapInstance, setMapInstance] = useState<maplibregl.Map | null>(null);

  const searchResultIndices = useMemo(
    () => buildSearchResultIndices(covers, searchResults),
    [searchResults, covers]
  );

  const searchResultPos = useMemo(
    () => getSearchResultPos(searchResultIndices, selectedIndex, !!selectedCover),
    [searchResultIndices, selectedIndex, selectedCover]
  );

  // Load cover data
  useEffect(() => {
    fetch("/fullCoversData.json")
      .then((r) => r.json())
      .then((data: CoverEntry[]) => setCovers(data));
  }, []);

  // Load search index
  useEffect(() => {
    initSearchIndex()
      .then(() => setSearchReady(true))
      .catch((err) => console.warn("Search index failed to load:", err));
  }, []);

  const handleCoverClick = useCallback(
    (cover: CoverEntry, index: number) => {
      setSelectedCover(cover);
      setSelectedIndex(index);
    },
    []
  );

  const handleDateSelect = useCallback(
    (date: Date) => {
      const cover = findCoverByDate(covers, date);
      if (cover) {
        const idx = covers.indexOf(cover);
        setFlyToIndex(idx);
        setSelectedCover(cover);
        setSelectedIndex(idx);
      }
    },
    [covers]
  );

  const handleFlyComplete = useCallback(() => {
    setFlyToIndex(null);
  }, []);

  const handleSearch = useCallback((query: string) => {
    if (!query.trim()) {
      setSearchResults(null);
      setSearchResultCount(null);
      return;
    }
    const results = searchCovers(query);
    if (results === null) return; // index not ready
    const map = new Map(results.map((r) => [r.id + ".jpg", r.score]));
    setSearchResults(map.size > 0 ? map : new Map());
    setSearchResultCount(map.size);
  }, []);

  const handleMapReady = useCallback((m: maplibregl.Map) => {
    setMapInstance(m);
  }, []);

  const handleMiniMapNavigate = useCallback(
    (lng: number, lat: number) => {
      mapInstance?.flyTo({ center: [lng, lat], duration: 800 });
    },
    [mapInstance]
  );

  const handleCloseModal = useCallback(() => {
    setSelectedCover(null);
  }, []);

  // Navigate: search results when search is active, otherwise all covers
  const handlePrev = useCallback(() => {
    const newIndex = navigatePrev(selectedIndex, covers.length, searchResultIndices);
    if (newIndex !== null) {
      setSelectedIndex(newIndex);
      setSelectedCover(covers[newIndex]);
      setFlyToIndex(newIndex);
    }
  }, [selectedIndex, covers, searchResultIndices]);

  const handleNext = useCallback(() => {
    const newIndex = navigateNext(selectedIndex, covers.length, searchResultIndices);
    if (newIndex !== null) {
      setSelectedIndex(newIndex);
      setSelectedCover(covers[newIndex]);
      setFlyToIndex(newIndex);
    }
  }, [selectedIndex, covers, searchResultIndices]);

  if (covers.length === 0) {
    return null; // Loading
  }

  const resultLabel = buildResultLabel(searchResultIndices, searchResultPos);
  const hasPrev = computeHasPrev(selectedIndex, searchResultIndices, searchResultPos);
  const hasNext = computeHasNext(selectedIndex, covers.length, searchResultIndices, searchResultPos);

  return (
    <div className="app">
      <CoverMap
        covers={covers}
        onCoverClick={handleCoverClick}
        flyToIndex={flyToIndex}
        onFlyComplete={handleFlyComplete}
        highlightedCovers={searchResults}
        onMapReady={handleMapReady}
      />

      <SearchBar
        onSearch={handleSearch}
        resultCount={searchResultCount}
        disabled={!searchReady}
      />

      <div className="overlay-card">
        <div className="overlay-card-inner">
          <p>
            Mit unserem Tool können Sie sich die Titelseite der Woche ansehen,
            in der Sie geboren wurden. Wählen Sie dafür erst das Jahr, dann den
            Monat, dann den Tag aus.
          </p>
          <DatePicker
            onDateSelect={handleDateSelect}
            minDate={MIN_DATE}
            maxDate={MAX_DATE}
          />
        </div>
      </div>

      <SearchMiniMap
        results={searchResults}
        covers={covers}
        mainMap={mapInstance}
        onNavigate={handleMiniMapNavigate}
      />

      <CoverModal
        cover={selectedCover}
        index={selectedIndex}
        totalCovers={covers.length}
        onClose={handleCloseModal}
        onPrev={handlePrev}
        onNext={handleNext}
        hasPrev={hasPrev}
        hasNext={hasNext}
        resultLabel={resultLabel}
      />
    </div>
  );
}

// src/App.vue
<script setup lang="ts">
import { ref, shallowRef, computed, onMounted } from 'vue'
import type maplibregl from 'maplibre-gl'
import CoverMap from './components/CoverMap.vue'
import CoverModal from './components/CoverModal.vue'
import SearchBar from './components/SearchBar.vue'
import SearchMiniMap from './components/SearchMiniMap.vue'
import type { CoverEntry } from './utils/coverLookup'
import { initSearchIndex, searchCovers } from './utils/searchIndex'
import {
  buildSearchResultIndices,
  getSearchResultPos,
  navigatePrev,
  navigateNext,
  buildResultLabel,
  computeHasPrev,
  computeHasNext,
} from './utils/searchSession'
import './styles/app.css'

const covers = ref<CoverEntry[]>([])
const selectedCover = ref<CoverEntry | null>(null)
const selectedIndex = ref(0)
const flyToIndex = ref<number | null>(null)
const searchReady = ref(false)
const searchResults = ref<Map<string, number> | null>(null)
const searchResultCount = ref<number | null>(null)
const mapInstance = shallowRef<maplibregl.Map | null>(null)

const searchResultIndices = computed(() =>
  buildSearchResultIndices(covers.value, searchResults.value)
)

const searchResultPos = computed(() =>
  getSearchResultPos(searchResultIndices.value, selectedIndex.value, !!selectedCover.value)
)

const resultLabel = computed(() =>
  buildResultLabel(searchResultIndices.value, searchResultPos.value)
)

const hasPrev = computed(() =>
  computeHasPrev(selectedIndex.value, searchResultIndices.value, searchResultPos.value)
)

const hasNext = computed(() =>
  computeHasNext(selectedIndex.value, covers.value.length, searchResultIndices.value, searchResultPos.value)
)

onMounted(async () => {
  const r = await fetch('/fullCoversData.json')
  covers.value = await r.json()
})

onMounted(async () => {
  try {
    await initSearchIndex()
    searchReady.value = true
  } catch (err) {
    console.warn('Search index failed to load:', err)
  }
})

function handleCoverClick(cover: CoverEntry, index: number) {
  selectedCover.value = cover
  selectedIndex.value = index
}

function handleFlyComplete() {
  flyToIndex.value = null
}

function handleSearch(query: string) {
  if (!query.trim()) {
    searchResults.value = null
    searchResultCount.value = null
    return
  }
  const results = searchCovers(query)
  if (results === null) return
  const map = new Map(results.map((r) => [r.id + '.jpg', r.score]))
  searchResults.value = map.size > 0 ? map : new Map()
  searchResultCount.value = map.size
}

function handleMapReady(m: maplibregl.Map) {
  mapInstance.value = m
}

function handleMiniMapNavigate(lng: number, lat: number) {
  mapInstance.value?.flyTo({ center: [lng, lat], duration: 800 })
}

function handleCloseModal() {
  selectedCover.value = null
}

function handlePrev() {
  const newIndex = navigatePrev(selectedIndex.value, searchResultIndices.value)
  if (newIndex !== null) {
    selectedIndex.value = newIndex
    selectedCover.value = covers.value[newIndex]
    flyToIndex.value = newIndex
  }
}

function handleNext() {
  const newIndex = navigateNext(selectedIndex.value, covers.value.length, searchResultIndices.value)
  if (newIndex !== null) {
    selectedIndex.value = newIndex
    selectedCover.value = covers.value[newIndex]
    flyToIndex.value = newIndex
  }
}
</script>

<template>
  <div v-if="covers.length > 0" class="app">
    <CoverMap
      :covers="covers"
      :fly-to-index="flyToIndex"
      :highlighted-covers="searchResults"
      @cover-click="handleCoverClick"
      @fly-complete="handleFlyComplete"
      @map-ready="handleMapReady"
    />

    <SearchBar
      :result-count="searchResultCount"
      :disabled="!searchReady"
      @search="handleSearch"
    />

    <SearchMiniMap
      :results="searchResults"
      :covers="covers"
      :main-map="mapInstance"
      @navigate="handleMiniMapNavigate"
    />

    <CoverModal
      :cover="selectedCover"
      :index="selectedIndex"
      :total-covers="covers.length"
      :has-prev="hasPrev"
      :has-next="hasNext"
      :result-label="resultLabel"
      @close="handleCloseModal"
      @prev="handlePrev"
      @next="handleNext"
    />
  </div>
</template>
